# Generated by Django 4.0.6 on 2022-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_articulo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='region',
            field=models.CharField(default='Centro', max_length=40),
            preserve_default=False,
        ),
    ]
