# Generated by Django 4.0.5 on 2022-08-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_articulo_cuerpo_avatar'),
        ('mainApp', '0006_articulo_region'),
    ]

    operations = [
    ]
