# Generated by Django 4.0.5 on 2022-08-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_articulo_cuerpo_alter_articulo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Posts/%d/%m/%Y'),
        ),
    ]
